config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }


  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  root to: "public/homes#top"
  get 'about' => 'public/homes#about'
  namespace :admin do
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :edit, :show, :update]
    resources :orders, only: [:show, :update]
    get '/' => 'homes#top'
  end

  scope module: :public do
    resources :items, only: [:index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]

    get 'customers/my_page' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw'


    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]

    get 'orders/comfirm' => 'orders#comfirm'
    get 'orders/complete' => 'orders#complete'
    resources :orders, only: [:new, :create, :index, :show]

  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/confirmations_controller.rb
# frozen_string_literal: true

class Admin::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admin/costomers_controller.rb
class Admin::CostomersController < ApplicationController
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
end

app/controllers/admin/order_details_controller.rb
class Admin::OrderDetailsController < ApplicationController
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/registrations_controller.rb
# frozen_string_literal: true

class Admin::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/costomers_helper.rb
module Admin::CostomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/costomers/edit.html.erb
<div class="container">
  <h4 class="ml-3"><%= @customer.first_name %><%= @customer.last_name %>さんの会員情報編集</h4>
  
  <%= form_with model: @customer, url: admin_customer_path do |f| %>
    <div class="row mt-5">
      <%= f.label :first_name, "氏名", class: "col-lg-2" %>
      <div class="col-lg-3 form-group">
        <%= f.text_field :first_name, class: "form-control" %>
      </div>
      <div class="col-lg-3 form-grup">
        <%= f.text_field :last_name, class: "form-control" %>
      </div>
    </div>

    <div class="row">
      <%= f.label :first_name_kana, "フリガナ", class: "col-lg-2" %>
      <div class="col-lg-3 form-group">
        <%= f.text_field :first_name_kana, class: "form-control" %>
      </div>
      <div class="col-lg-3 form-group" >
        <%= f.text_field :last_name_kana, class: "form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <%= f.label :postal_code, "郵便番号", class: "col-lg-2" %>
      <div class="col-lg-3">
        <%= f.text_field :postal_code, class: "form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <%= f.label :address, "住所", class: "col-lg-2"%>
      <div class="col-lg-6">
        <%= f.text_field :address, class: "form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <%= f.label :telephone_number, "電話番号", class: "col-lg-2" %>
      <div class="col-lg-3">
        <%= f.text_field :telephone_number, class: "form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <%= f.label :email , "メールアドレス", class: "col-lg-2" %>
      <div class="col-lg-3">
        <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <%= f.label :is_deleted , "会員ステータス", class: "col-lg-2" %>
      <div class="form-check ml-3">
        <%= f.radio_button :is_deleted, false, class: "form-check-input" %>
        <%= f.label :is_deleted_false, "有効", class: "form-check-label" %>
      </div>
      <div class="form-check ml-3">
        <%= f.radio_button :is_deleted, true, class: "form-check-input" %>
        <%= f.label :is_deleted_true, "退会", class: "form-check-label"%>
      </div>
    </div>

    <div class="actions">
      <%= f.submit "変更を保存", class: "btn btn-success offset-2 mb-5 px-4" %>
    </div>
  <% end %>
  </row>
</div>

app/views/admin/costomers/index.html.erb
<div class="container">
  <h4 class="ml-3">会員一覧</h4>
  <table class="table mt-5">
    <tr class="thead-light">
      <th>会員ID</th>
      <th>氏名</th>
      <th>メールアドレス</th>
      <th>ステータス</th>
    </tr>
    <% @customers.each do |customer| %>
    <tr>
      <td><%= customer.id %></td>
      <td><%= link_to admin_customer_path(customer.id), class: "text-dark" do %>
            <%= customer.first_name %><%= customer.last_name %></td>
          <% end %>
      <td><%= customer.email %></td>
      <td><% if customer.is_deleted == false %>
            <span class="text-success font-weight-bold">有効</span>
          <% else %>
            <span class="text-secondary font-weight-bold">退会</span>
          <% end %></td>
    </tr>
    <% end %>
  </table>

</div>

app/views/admin/costomers/show.html.erb
<div class="container">
  <h4 class="ml-3"><%= @customer.first_name %><%= @customer.last_name %>さんの会員詳細</h4>
  <div class="row mt-4">
    <div class="col-lg-6">
      <table class="table table-borderless">
        <tr>
          <td>会員ID</td>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <td>氏名</td>
          <td><%= @customer.first_name %> <%= @customer.last_name %></td>
        </tr>
        <tr>
          <td>フリガナ</td>
          <td><%= @customer.first_name_kana %> <%= @customer.last_name_kana %></td>
        </tr>
        <tr>
          <td>郵便番号</td>
          <td><%= @customer.postal_code %></td></td>
        </tr>
        <tr>
          <td>住所</td>
          <td><%= @customer.address %></td>
        </tr>
        <tr>
          <td>電話番号</td>
          <td><%= @customer.telephone_number %></td>
        </tr>
        <tr>
          <td>メールアドレス</td>
          <td><%= @customer.email %></td>
        </tr>
        <tr>
          <td>会員ステータス</td>
          <td><% if @customer.is_deleted == false %>
                <span class="text-success font-weight-bold">有効</span>
              <% else %>
                <span class="text-secondary font-weight-bold">退会</span>
              <% end %></td>
        </tr>
      </table>
      <div class="mb-5">
        <%= link_to "編集する", {controller: "admin/customers", action: "edit"}, class: "btn btn-success mr-5 ml-5" %>
        <%= link_to "注文履歴一覧を見る", {controller: "admin/homes", action: "top"}, class: "btn btn-primary" %>
      </div>
    </div>
  </div>

</div>
Footer
© 2022 GitHub, Inc.
Footer navigation
Terms
Priv

app/views/admin/homes/top.html.erb
<div class="container">
  <h4 class="ml-3">注文履歴一覧</h4>
  <table class="table col-md-10 mt-3">
    <tr class="thead-light">
      <th>購入日時</th>
      <th>購入者</th>
      <th>注文個数</th>
      <th>注文ステータス</th>
    </tr>
    <% @orders.each do |order| %>
    <tr>
      <td><%= link_to admin_order_path(order.id), class: "text-decoration-none" do %>
            <%= order.created_at.strftime("%Y/%m/%d %H:%M:%S") %>
          <% end %></td>
      <td><%= order.customer.first_name %><%= order.customer.last_name %></td>
      <td><% order.order_details.each do |order_detail| %>
            <% @total_amount += order_detail.amount %>
          <% end %>
          <%= @total_amount %></td>
      <td><%= order.order_status_i18n %></td>
    </tr>
    <% end %>
  </table>
</div>

app/views/admin/items/edit.html.erb
<h1>商品編集</h1>

<%= form_with model: @item, url: admin_item_path do |f| %>
  <label for="Image">商品画像</label>
    <p><%= f.file_field :image, placeholder: "Image",accept: "image/*" %></p>
      <label for="inputName">商品名</label>
        <p><%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"Name"%></p>
          <label for="inputIntroduction">商品説明</label>
            <p><%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", placeholder:"Inputintroduction"%></p>
            <label for="inputPrice">税抜価格</label>
          <p><%= f.text_area :price, autofocus: true, id:"inputPrice", placeholder:"InputPrice"%>円</p>
        <%= f.radio_button :is_active, true %>
      <%= f.label :is_active_is_order, "販売中" %>
    <%= f.radio_button :is_active,  false %>
  <%= f.label :is_active_is_order, "販売停止中" %>
<p>
<%= f.submit '変更を保存', class: "btn btn-secondary" %>
</p>
<% end %>

app/views/admin/items/index.html.erb
<h1>商品一覧</h1>
<li>
<%= link_to "新規登録",new_admin_item_path ,class: "btn btn-sm btn-success" %>
</li>
<table class="table table-hover table-inverse">
 
  <thead>
    <tr>
     <th>商品ID</th>
      <th>商品名</th>
       <th>税抜価格</th>
        <th>ステータス</th>
        </tr>
      </thead>
    <tbody>
 <% @items.each do |item| %>
　<tr>
    　<td>
    　  <%= item.id %>
    　    </td>
    　     <td>
    　      <%= link_to admin_item_path(item) do %>
             <%= item.name %>
             <% end %>
        　     </td>
              <td>
              <%= item.price %>
            </td>
            <td>
            <%= item.show_status %>
          </td>
        </tr>
    <% end %>
</tbody>
</table>

app/views/admin/items/new.etml.erb
<h2>商品新規登録</h2>
<%= form_with model: @item, url: admin_items_path do |f| %>
 <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "選択して下さい" %>
<h4>商品画像</h4>
<%= f.file_field :image, accept: "image/*", class: "w-100" %>

<h4>商品名</h4>
  <%= f.text_field :name %>

<h4>商品説明文</h4>
  <%= f.text_area :introduction %>

<h4>税込価格</h4>
  <a><%= f.text_field :price %>円</a>

<h4>販売ステータス</h4>
<%= f.radio_button :is_active, true %>
<%= f.label :is_active_is_order, "販売中" %>
<%= f.radio_button :is_active, false %>
<%= f.label :is_active_is_order, "販売停止中" %>

<p>
<%= f.submit '登録', class: "btn btn-success" %>
</p>

<% end %>

app/views/admin/items/show.html.erb
<h2>商品詳細</h2>
  <table class="table">
    <thead>
    <tr>
    <th></th>
     <th>商品名</th>
      <th>商品説明</th>
       <th>税込価格</th>
        <th>販売ステータス</th>
        </tr>
      </thead>
    <tbody>
      <tr>
        <td>
          <%= image_tag @item.get_image(100,100) %>
        </td>
         <td>
         <%= @item.name %>
        </td>
       <td>
      <%= @item.introduction %>
    </td>
  <td>
<a><%= @item.price %>円</a>
</td>
<td>
<%= @item.show_status %>
</td>
<li>
  <%= link_to "編集", edit_admin_item_path %>
</li>
</tr>
</tbody>
</table>

app/views/admin/orders/show.html.erb
 <div class="container">
  <h4 class="ml-3">注文履歴詳細</h4>
  <table class="table table-borderless mt-4 col-lg-7">
    <tr>
      <td class="font-weight-bold">購入者</td>
      <td><%= @order.customer.first_name %><%= @order.customer.last_name %></td>
    </tr>
    <tr>
      <td class="font-weight-bold">注文日</td>
      <td><%= @order.created_at.strftime("%Y/%m/%d")%></td>
    </tr>
    <tr>
      <td class="font-weight-bold">配送先</td>
      <td>〒<%= @order.postal_code %> <%= @order.address %> <%= @order.name %></td>
    </tr>
    <tr>
      <td class="font-weight-bold">支払方法</td>
      <td><%= @order.payment_method_i18n %></td>
    </tr>
    <tr>
      <td class="font-weight-bold">注文ステータス</td>
      <td><%= form_with model: @order, url: admin_order_path(@order.id) do |f| %>
            <%= f.select :order_status, Order.order_statuses.keys.map { |k| [t("enums.order.order_status.#{k}"), k] }, {}, class: "form-control-sm" %>
            <%= f.submit '更新', class: "btn btn-success btn-sm" %>
          <% end %></td>
    </tr>
  </table>
  <div class="row my-5 mx-0">
    <table class="table col-lg-7 ">
      <thead class="thead-light">
        <th>商品名</th>
        <th>単価(税込)</th>
        <th>数量</th>
        <th>小計</th>
        <th>製作ステータス</th>
      </thead>
      <tbody>
      <% @order_details.each do |order_detail| %>
        <tr>
          <td><%= order_detail.item.name %></td>
          <td><%= order_detail.price.to_s(:delimited) %></td>
          <td><%= order_detail.amount %></td>
          <td><%= (order_detail.price * order_detail.amount).to_s(:delimited) %></td>
          <td><%= form_with model: order_detail, url: admin_order_detail_path(@order.id, order_detail.id) do |f| %>
                <%= f.select :making_status, OrderDetail.making_statuses.keys.map { |k| [t("enums.order_detail.making_status.#{k}"), k] }, {}, class: "form-control-sm" %>
                <%= f.submit '更新', class: "btn btn-success btn-sm" %>
              <% end %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
    
    <table class="table table-borderless col-lg-3 col-6 ml-lg-5 mt-lg-0 mt-4">
      <tr>
        <td class="font-weight-bold">商品合計</td>
        <td><%= (@order.total_payment - @order.postage).to_s(:delimited) %>円</td>
      </tr>
      <tr>
        <td class="font-weight-bold">送料</td>
        <td><%= @order.postage %>円</td>
      </tr>
      <tr>
        <td class="font-weight-bold">請求金額合計</td>
        <td class="font-weight-bold"><%= @order.total_payment.to_s(:delimited) %>円</td>
      </tr>
    </table>
  </div>
    
  
</div>

app/views/homes/thanks.html.erb
<div class="container-fluid">
 <div class="text-center">


  <%= image_tag 'thank_you.png', class: "thanksbox" %>

  <h3 class="thankscomment">ご購入ありがとうございました！</h3>

  <script>
  $(function() {
    $('.thanksbox, .thankscomment').hide().fadeIn(3000)

    });
</script>

 </div>
</div>